
# Site language
lang: en-US

# Site title
title: "sphen"

# A description of your site for meta tag, search engine results.
description: "I'm sphen, and this is my website - a depot for things I learn and create. Thanks for visiting."

# The subpath of your site, e.g. /blog, for generating urls.
#baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
#url: "sphen.net"

# Favicon
favicon: ../images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
#google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Tags
    url: /tags/
  - text: Projects
    url: ../projects/

# The shortname for your Disqus site to enable comments.
#disqus: 

# Colors
#accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; sphen 2021"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 8
paginate_path: './projects/page:num/'


# Permalinks
permalink: /:categories/:title
#permalink: pretty

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
